### ISSUE TITLE
Use the java-openliberty stack instead of the java-microprofile stack

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/guide-nexus-repository-integration#10]
Kabanero 0.6.0 officially deprecated the java-microprofile stack. The guide should use the java-openliberty stack instead.

**Comment by nastacio** [comment]
Related to https://github.com/kabanero-io/draft-guide-onboarding-with-che/issues/4

**Comment by mingcyu** [comment]
Update needs to be made to the Nexus guide. Steve Kinder mentioned that there might be a missing guide, so need to work to figure out if there is more behind this

**Comment by mingcyu** [comment]
@sghung Hi Steven, can you take a look at the current guide to see what is needed and test if it works with current levels?

**Comment by SueChaplain** [comment]
Issue moved to new repo: https://github.com/kabanero-io/guides/issues/44
